language en_US.UTF-8
syntax on
filetype plugin indent on
set nocompatible
set encoding=utf-8

let mapleader = ","

" editor general
set mouse=a
set tabstop=8
set softtabstop=2
set shiftwidth=2
set textwidth=0
set expandtab
set number
set numberwidth=4
set scrolloff=3
set nowrap
set smartcase
set hlsearch
set incsearch
set linebreak
set laststatus=2
set statusline=%f%=(%l,%c)
set spelllang=en_us
set whichwrap=bs<>hl[]
set autoindent
" disable "comment continuation" (gets overridden on load, have to resort to this)
autocmd FileType * set formatoptions-=ro
autocmd FileType markdown setlocal spell
autocmd FileType markdown setlocal complete+=kspell
hi LineNr ctermfg=7

" ignore just a q press. h*ck i dislike this command...
map q <Nop>
" yank to clipboard
vnoremap <leader>c "+y

" plugin
call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'ntpeters/vim-better-whitespace'
Plug 'mhinz/vim-signify'

call plug#end()

" dim highlight of trailing whitespace
highlight ExtraWhitespace ctermbg=7

" diff
highlight SignColumn ctermbg=none
set updatetime=100
