language en_US.UTF-8
syntax on
filetype plugin indent on
set nocompatible
set encoding=utf-8

let mapleader = ","

" editor general
set mouse=a
set tabstop=8
set softtabstop=2
set shiftwidth=2
set textwidth=0
set expandtab
set number
set numberwidth=4
set scrolloff=3
set nowrap
set smartcase
set hlsearch
set incsearch
set linebreak
set laststatus=2
set statusline=%f%m\ %y%=%l/%L,%c " (based on https://nkantar.com/blog/2017/01/my-vim-statusline/)
set spelllang=en_us
set spellcapcheck= " disable capitalization
set whichwrap=bs<>hl[]
set autoindent
set fillchars+=vert:│
" disable "comment continuation" (gets overridden on load, have to resort to this)
autocmd FileType * set formatoptions-=ro
autocmd FileType markdown setlocal spell
autocmd FileType markdown setlocal complete+=kspell
hi LineNr ctermfg=7
hi VertSplit cterm=none ctermfg=0

" ignore just a q press. h*ck i dislike this command...
map q <Nop>
" yank to clipboard
vnoremap <leader>c "+y
" move through softlines (based on https://stackoverflow.com/a/21000307)
nnoremap <expr> <Down> v:count ? 'j' : 'gj'
nnoremap <expr> <Up> v:count ? 'k' : 'gk'

" netrw (based on https://stackoverflow.com/q/53538591)
let g:netrw_banner=0 " removes top banner
let g:netrw_liststyle=3 " tree-styled
let g:netrw_browse_split=4 " open file in last tab (do not replace browser)
let g:netrw_altv=1 " opens on right side
let g:netrw_winsize=25 " panel width

" plugin
call plug#begin("$HOME/.config/vim/plugged")

Plug 'tpope/vim-sensible' " insane default
Plug 'ntpeters/vim-better-whitespace' " ws
Plug 'airblade/vim-gitgutter' " git inline

call plug#end()

" dim highlight of trailing whitespace
hi ExtraWhitespace ctermbg=7

" diff
hi SignColumn ctermbg=none
set updatetime=100

