#!/usr/bin/env zsh

# ^Z toggles between suspend and resume
toggle_suspend() {
  local suspended=${(M)#jobstates:#suspended:*}
  if (( suspended )); then
    zle push-input
    zle -I; fg
  else
    zle suspend
  fi
}
