#!/usr/bin/env zsh

# ^Z toggles between suspend and resume
toggle_suspend() {
  local suspended=${(M)#jobstates:#suspended:*}
  if (( suspended )); then
    zle push-input
    zle -I; fg
    zle get-line
    zle reset-prompt
  else
    zle suspend
  fi
}
